#!/usr/bin/env python3
"""Regenerate embedded instructions from role references."""
from pathlib import Path
import json
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]


def render(role):
    config = json.loads((ROOT / "agents/roles.json").read_text(encoding="utf-8"))[role]
    refs = ["common"] + config["references"]
    body = "\n\n".join((ROOT / "skills/frontend-flow/references" / (r + ".md")).read_text(encoding="utf-8").strip() for r in refs)
    if "'''" in body:
        raise ValueError("TOML literal delimiter inside role instructions")
    header = "# Generated by scripts/generate_agents.py.\n"
    for key in ("name", "description", "model", "model_reasoning_effort", "sandbox_mode"):
        value = role if key == "name" else config.get(key)
        if value is not None:
            header += key + " = " + json.dumps(value, ensure_ascii=False) + "\n"
    result = header + "\ndeveloper_instructions = '''\n" + body + "\n'''\n"
    tomllib.loads(result)
    return result


def main():
    check = "--check" in sys.argv
    roles = json.loads((ROOT / "agents/roles.json").read_text(encoding="utf-8"))
    bad = []
    for role in roles:
        target = ROOT / "agents" / (role + ".toml")
        expected = render(role)
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != expected:
                bad.append(role)
        else:
            target.write_text(expected, encoding="utf-8", newline="\n")
    if bad:
        raise SystemExit("Outdated generated agents: " + ", ".join(bad))
    print(str(len(roles)) + " agents " + ("verified" if check else "generated"))


if __name__ == "__main__":
    main()
